version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: eshop_postgres
    environment:
      POSTGRES_DB: eshop_db
      POSTGRES_USER: eshop_user
      POSTGRES_PASSWORD: eshop_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: