version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: eshop_postgres
    environment:
      POSTGRES_DB: eshop_db
      POSTGRES_USER: eshop_user
      POSTGRES_PASSWORD: eshop_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: eshop_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "9090:80"
    depends_on:
      - postgres

volumes:
  postgres_data: